external/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('recruit/', views.recruit_list, name='recruit'),
    path('recruit/create/', views.recruit_new, name='recruit_new'),
    path('recruit/<int:pk>/', views.recruit_detail, name='recruit_detail'),
    path('recruit/<int:pk>/edit/', views.recruit_edit, name='recruit_edit'),
    path('recruit/<int:pk>/delete/', views.recruit_delete, name='recruit_delete'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('portfolio/create/', views.portfolio_new, name='port_new'),
    path('portfolio/<int:pk>/edit/', views.port_edit, name='port_edit'),
    path('portfolio/<int:pk>/delete/', views.port_delete, name='port_delete'),
]

money/urls.py
from django.urls import path

from money import views

app_name = 'money'

urlpatterns=[
    path('', views.check_money, name='check_money'),
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from ckeditor_uploader import views as uploader_views

urlpatterns = [
    path('', include('external.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('intranet/', include('internal.urls')),
    path('photobook/', include('photobook.urls')),
    path('money/', include('money.urls')),
    path('infoboard/', include('infoboard.urls')),
    path('ckeditor/upload/', uploader_views.upload, name='ckeditor_upload'),
    path('ckeditor/browse/', uploader_views.browse, name='ckeditor_browse'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

external/models.py
from django.db import models
from django.urls import reverse

from accounts.models import PiroUser

class Recruitment(models.Model):
    title = models.CharField(max_length=50, verbose_name='제목')
    content = models.TextField(verbose_name='내용')
    img = models.ImageField(blank=True, upload_to="recruit", verbose_name='이미지')
    created_at = models.DateField(auto_now_add=True)

    author = models.ForeignKey(PiroUser, on_delete=models.CASCADE, verbose_name='글쓴이')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('home:recruit_detail', args=[self.pk])


class Portfolio(models.Model):
    title = models.CharField(max_length=50, verbose_name='프로젝트 이름')
    team = models.CharField(max_length=50, verbose_name='팀이름')
    content = models.TextField(verbose_name='내용')
    image = models.ImageField(blank=True, upload_to="portfolio", verbose_name="사진")
    pironumber = models.PositiveIntegerField(verbose_name="기수")

    def __str__(self):
        return f'{self.pironumber}기 {self.title}'

external/forms.py
from django import forms
from .models import Recruitment, Portfolio


class NoticeForm(forms.ModelForm):
    class Meta:
        model = Recruitment
        fields = ['title', 'content', 'img']

class PortForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['image'].help_text = '290 X 290의 정사각형 이미지를 삽입해주세요.'

    class Meta:
        model = Portfolio
        fields = '__all__'

external/views.py
from django.contrib import messages
from django.db.models import Max
from django.shortcuts import render, redirect,get_object_or_404
from .forms import NoticeForm, PortForm
from .models import Recruitment, Portfolio


def home(request):
    return render(request, 'main.html')

def portfolio(request):
    qs = Portfolio.objects.all()
    maxpiro = Portfolio.objects.aggregate(Max('pironumber'))
    if maxpiro.get("pironumber__max") == None:
        return redirect("home:port_new")
    maxno = maxpiro.get("pironumber__max") + 1
    return render(request, 'external/port_list.html',{
        'port_list': qs,
        'maxno': maxno,
        'range': range(1,maxno)
    })

def portfolio_new(request, port=None):
    if request.method == 'POST':
        form = PortForm(request.POST, request.FILES, instance=port)
        if form.is_valid():
            form.save()
            return redirect("home:portfolio")
        else:
            return redirect("home:home")
    else:
        form = PortForm(instance=port)
        return render(request, 'external/create_port.html', {
            'form': form,
        })

def port_edit(request, pk):
    port = get_object_or_404(Portfolio, pk=pk)
    return portfolio_new(request, port)

def port_delete(request, pk):
    if request.user.is_authenticated:
        if request.user.is_admin:
            port = Portfolio.objects.get(id=pk)
            port.delete()
            return redirect('home:portfolio')
        else:
            return redirect('home:home')
    else:
        return redirect('home:home')

def recruit_list(request):
    qs = Recruitment.objects.all().order_by('-id')
    return render(request, 'external/recruit.html', {
        'notice_list': qs,
    })

def recruit_new(request, post=None):
    if request.method == 'POST':
        form = NoticeForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect("home:recruit")
        else:
            messages.error(request, '양식이 잘못되었습니다. 다시 시도해주세요.')
            return redirect("home:recruit")
    else:
        form = NoticeForm(instance=post)
        return render(request, 'external/create_recruit.html', {
            'form': form,
        })

def recruit_detail(request, pk):
    post = get_object_or_404(Recruitment, pk=pk)
    return render(request,'external/detail_recruit.html', {
        'post': post,
    })

def recruit_edit(request, pk):
    post = get_object_or_404(Recruitment, pk=pk)
    return recruit_new(request, post)

def recruit_delete(request, pk):
    if request.user.is_authenticated:
        if request.user.is_admin:
            post = Recruitment.objects.get(id=pk)
            post.delete()
            return redirect('home:recruit')
        else:
            return redirect('home:home')
    else:
        return redirect('home:home')

external/templates/external/about.html
{% load staticfiles %}

<section id="about" class="home-section" style="background-color: #ffffff">
  <div class="container">
    <div class="row" style="padding-bottom: 1.3%">
      <div class="offset-lg-2 col-lg-8">
        <div class="section-heading">
          <h5>ABOUT US</h5>
          <div class="heading-line"></div>
          <p style="font-family: 'Noto Sans KR'">웹 개발에 관심 있는 모두를 위한 연합동아리</p>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-lg-6 about-img">
        <img src="{% static 'img/piro_about.jpg' %}" alt="">
      </div>

      <div class="col-lg-6 content">
        <h3>방학은 짧고 인생은 깁니다.</h3>
        <p>
          피로그래밍은 프로그래밍 공부를 하고 싶으나 어디서부터 시작해야 할지 막막한 비전공자들이 Python과 Django 프레임워크를 기반으로 웹 개발을 배우고
          자신만의 웹서비스를 만드는 동아리입니다.</p>
        <p>비전공자 기준으로 기초부터 차근차근 쉽게 공부하며 방학 동안 집중적으로 코딩에 전념하여 프로그래밍(웹 개발)의
          기반을 확보하는데 그 목표가 있습니다.
        </p>
        <p>
          여러분들을 위한 동아리입니다:<br>
          ✔ 프로그래밍을 배우고 싶지만, 첫 발을 내딛기 어려운 사람<br>
          ✔ 비전공자라서 프로그래밍 동아리에 지원조차 못했던 사람<br>
          ✔ 웹 개발에 관심 있는 디자인 전공자<br>
          ✔ 컴퓨터 관련 학과 전공자이지만 웹 개발 공부를 하고 싶은 사람<br>
          ✔ 웹 서비스로 구현하고 싶은 아이디어가 있는 사람<br>
        </p>
      </div>
    </div>
  </div>
  <div class="container wow zoomIn">
    <div class="row counters">
      <div class="col-lg-3 col-6 text-center">
        <p>동아리 역사</p>
        <span class="counter">6</span><h1>년</h1>
      </div>
      <div class="col-lg-3 col-6 text-center">
        <p>참여 학생 총</p>
        <span class="counter">360</span><h1>명</h1>
      </div>
      <div class="col-lg-3 col-6 text-center">
        <p>전국 참여 대학</p>
        <span class="counter">18</span><h1>곳</h1>
      </div>
      <div class="col-lg-3 col-6 text-center">
        <p>프로젝트 총</p>
        <span class="counter">72</span><h1>개</h1>
      </div>
    </div>
  </div>
</section>

external/templates/external/activity.html
{% load staticfiles %}

<link rel="stylesheet" href="{% static 'css/activity.css' %}">

<section class="activity" id="activity">
    <div class="activity-info wow fadeInDown">
        <div class="row">
            <div class="col info-content">
            <h5>피로그래밍 활동</h5>
            <div class="heading-line"></div>
            <p style="font-family: 'Noto Sans KR'">방학 중에는 인터넷 강의, 선배 기수의 강의를 통해 웹 개발을 공부하고, 직접 만들고 싶은 웬서비스를 기획해 팀 단위로 나뉘어 협업한 프로젝트를 발표합니다.
            <br>방학 6주차부터 학기 중에는 선배 기수에서 선정한 프로그래밍 실력 향상에 도움이 되는 여러 주제를 직접 공부하고 발표하는 세션을 진행합니다.</p>
            </div>
        </div>
    </div>
    <div class="activity-content">
        <div class="row justify-content-center">
            <figure class="modi snip1200">
              <img src="{% static 'img/piro_activity_1.jpg' %}" alt="piro_activity_1" />
              <figcaption>
                <p>웹으로 문서를 공유하기 위한 약속인 마크업 언어 (HTML / CSS)를 배웁니다.<br><br>
                웹에서 동작하는 JavaScript와 Bootstrap을 이용하여 동적인 웹페이지를 만드는 것에 대해 배웁니다.</p>
                <div class="heading">
                  <h2>Week <span> 01</span></h2>
                </div>
              </figcaption>
            </figure>
            <figure class="modi snip1200">
              <img src="{% static 'img/piro_activity_2.jpg' %}" alt="piro_activity_2" />
              <figcaption>
                <p>Python을 통해 프로그래밍 언어 문법을 익히고 객체 지향 언어의 특징을 익힙니다.<br><br>
                소스 코드의 버전 관리 도구인 Git과 Github이라는 플랫폼의 사용 방법에 대해 배웁니다.</p>
                <div class="heading">
                  <h2>Week <span> 02</span></h2>
                </div>
              </figcaption>
            </figure>
            <figure class="modi snip1200">
              <img src="{% static 'img/piro_activity_3.jpg' %}" alt="piro_activity_3" />
              <figcaption>
                <p>Django를 통해 웹브라우저와 서버의 상호작용에 대해 배웁니다.<br><br>
                    Django 프레임워크의 구조를 이해하고 URL설계, MTV 패턴의 유기적인 연결, ORM, Django 폼 등 장고의 주요 기능에 대해 배웁니다.</p>
                <div class="heading">
                  <h2>Week <span> 03-05</span></h2>
                </div>
              </figcaption>
            </figure>
            <figure class="modi snip1200">
              <img src="{% static 'img/piro_activity_4.jpg' %}" alt="piro_activity_4" />
              <figcaption>
                <p>프로젝트를 개발, 완성, 배포하고 세션(프로젝트 발표)을 진행합니다.</p>
                <div class="heading">
                  <h2>Week <span> 06-08</span></h2>
                </div>
              </figcaption>
            </figure>
        </div>
    </div>
</section>

<div class="wow fadeInLeft">
    <div class="row" id="schedule">
        <div class="col info-content">
        <h5>피로그래밍 상반기 활동 일정</h5>
        <div class="heading-line"></div>
        <img src="{% static 'img/piro_timeline.png' %}" alt="piro_timeline" />
        </div>
    </div>
</div>

external/templates/external/create_port.html
{% extends 'base.html' %}

{% block title %}
피로그래밍 - 프로젝트 추가하기
{% endblock %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
{% if user.is_admin %}

<style>
    #image-clear_id{
        display: none;
    }

    #div_id_image label{
        display: none;
    }
    #rec_upld{
        color: #2C3E52; 
        border: solid 1px #2C3E52;
    }

    #rec_upld:hover{
        background-color: #2C3E52;
        color:white;
    }

    .nanum{
        margin-bottom: 25px;
    }

</style>

<script>
function change_port() {
    document.getElementById("option4").href="{% url "home:recruit" %}";
    document.getElementById("option1").href="{% url "home:home" %}#about";
    document.getElementById("option2").href="{% url "home:home" %}#activity";
    document.getElementById("option3").style.color = 'white';
    document.getElementById("option3").href = "{% url "home:portfolio" %}";
}
change_port();

</script>

<div class="col-sm-10" style="margin:50px auto;">
    <h2 class="create-title">프로젝트 추가하기</h2>
    <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
        {% csrf_token %}
            <div class="signup-form nanum">
                {{ form.title|as_crispy_field }}
            </div>
            <div class="signup-form nanum">
                {{ form.team|as_crispy_field }}
            </div>
            <div class="signup-form nanum">
                {{ form.pironumber|as_crispy_field }}
            </div>
            <div class="signup-form nanum">
                {{ form.content|as_crispy_field }}
            </div>
            <div class="signup-form nanum">
                {{ form.image|as_crispy_field }}
            </div>
        <input type="submit" value="등록하기" id="rec_upld" class="btn btn-navy"/>
    </form>
</div>
{% else %}
<script>
    alert('접근 권한이 없는 페이지입니다.');
    window.location.href = "{% url "home:home" %}";
</script>
{% endif %}

{% endblock %}

external/templates/external/create_recruit.html
{% extends 'base.html' %}

{% block title %}
피로그래밍 - 모집글
{% endblock %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
{% if user.is_admin %}

<style>
    #img-clear_id{
        display: none;
    }

    #div_id_img label{
        display: none;
    }
    #rec_upld{
        color: #2C3E52; 
        border: solid 1px #2C3E52;
    }
    #rec_upld:hover{
        background-color: #2C3E52;
        color:white;
    }

    .nanum{
        margin-bottom: 25px;
    }

</style>

<script>
function change_recruit() {
    document.getElementById("option4").style.color = 'white';
    document.getElementById("option1").href="{% url "home:home" %}#about";
    document.getElementById("option2").href="{% url "home:home" %}#activity";
    document.getElementById("option3").href="{% url "home:portfolio" %}";
}
change_recruit();

</script>

<div class="col-sm-10" style="margin:50px auto;">
    <h2 class="create-title">모집글 쓰기</h2>
    <form action="" method="post" enctype="multipart/form-data" autocomplete="off">
        {% csrf_token %}
            <div class="signup-form nanum">
                {{ form.title|as_crispy_field }}
            </div>
            <div class="signup-form nanum">
                {{ form.content|as_crispy_field }}
            </div>
            <div class="signup-form nanum">
                {{ form.img|as_crispy_field }}
            </div>
            <input type="submit" value="등록하기" id="rec_upld" class="btn btn-navy"/>
    </form>
</div>
{% else %}
<script>
    alert('접근 권한이 없는 페이지입니다.');
    window.location.href = "{% url "home:home" %}";
</script>
{% endif %}

{% endblock %}

external/templates/external/detail_recruit.html
{% extends 'base.html' %}

{% block title %}
{{ post.title }}
{% endblock %}

{% block content %}

<script>
function change_recruit() {
    document.getElementById("option4").style.color = 'white';
    document.getElementById("option1").href="{% url "home:home" %}#about";
    document.getElementById("option2").href="{% url "home:home" %}#activity";
    document.getElementById("option3").href="{% url "home:portfolio" %}";
}
change_recruit();

</script>

<div class="col-sm-7" style="margin:50px auto;">
    <h2 class="nanum">{{ post.title }}</h2>
    <hr/>
    {% if post.img %}
        <img src="{{ post.img.url }}" style="max-width: 100%;"/>
        <br>
        <br>
    {% endif %}
    <div class="nanum" style="padding:16px;">
        <p style="white-space: pre-wrap">{{ post.content|urlize }} </p>
    </div>
    <hr/>
    <div style="display: inline-block; float:left;">
        <a class="btn-navy" href="{% url "home:recruit" %}" style="text-decoration: none;">목록</a>
    </div>
    {% if user.is_admin %}
    <div style="display: inline-block; float:right;">
        <a class="btn-navy" href="{% url "home:recruit_edit" post.pk %}" style="margin-right: 5px; text-decoration: none;">수정</a>
        <a class="btn-navy" href="{% url "home:recruit_delete" post.pk %}" onclick="return confirm('삭제하시겠습니까?');" style="text-decoration: none;">삭제</a>
    </div>
    {% endif %}
    <br>
</div>
{% endblock %}

external/templates/external/intro.html
{% load staticfiles %}
<section id="home">
<div id="carouselExampleCaptions" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleCaptions" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleCaptions" data-slide-to="1"></li>
    </ol>

    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{% static 'img/piro_intro_1.jpg' %}" class="d-block w-100" alt="리크루팅 공지">
        </div>
        <div class="carousel-item">
            <img src="{% static 'img/piro_intro_2.png' %}" class="d-block w-100" alt="리크루팅 공지 #2">
        </div>
    </div>

    <a class="carousel-control-prev" href="#carouselExampleCaptions" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>

    <a class="carousel-control-next" href="#carouselExampleCaptions" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>
</section>
<div class="dodobird" id="progress-container">
    <div class="progress-bar" id="urBar"></div>
</div>

external/templates/external/port_list.html
{% extends 'base.html' %}

{% block title %}
피로그래밍 - 프로젝트
{% endblock %}

{% block content %}

{% load static %}

<style>
   .img-header {
        background-image: url("{% static "img/port.jpg" %}");
    }

    .header-cover {
        background-color: rgba(47,65,84, 0.8);
    }

    .portfolio-box{
        padding: 50px 20px 50px 20px;
    }

    .text{
        font-family: "Nanum Gothic";
        font-weight:bold;
    }

</style>

<script type="text/javascript">
    function viewDiv(idx) {
        if (idx != 0 && idx != 200){
            for (var i=1; i<{{ maxno }}; i++){
            $(".div"+i).css("display", "none");
            }
            $(".div"+idx).css("display", "");
        }
        else{
            for (var i=1; i<{{ maxno }}; i++){
            $(".div"+i).css("display", "");
            }
        }
    }

    function selectIndex(selectObj) {
        var idx = selectObj.value;
        viewDiv(idx);
    }
</script>

<script>
function change_port_list() {
    document.getElementById("option3").style.color = 'white';
    document.getElementById("option3").href = "{% url "home:portfolio" %}";
    document.getElementById("option1").href="{% url "home:home" %}#about";
    document.getElementById("option2").href="{% url "home:home" %}#activity";
    document.getElementById("option3").href="#";
}
change_port_list();
</script>

<section class="wow fadeInUp">
    <div class="img-header">
        <div class="header-content">
            <h3 class="header-title">PORTFOLIO</h3>
            <p class="header-text">
                피로그래밍에서 작업한 프로젝트에 대한 내용을 확인 할 수 있습니다.
                <br>아래에서 기수를 선택하여 각 기수에서 완성한 프로젝트를 확인해보세요!
            </p>
        </div>
        <div class="header-cover"></div>
    </div>
    <div class="portfolio-box">
        <div class="portfolio-container" style="margin:20px 0px 10px 0px;">
            <div class="portfolio-header">
                <select name="select" onchange="javascript:selectIndex(this)">
                    <option value="0" disabled selected>기수 선택</option>
                    <option value="200">전체 보기</option>
                    {% for i in range %}
                    <option value="{{ i }}">{{ i }}기</option>
                    {% endfor %}
                </select>
            </div>
        </div>
        <div class="portfolio-main">
            <!-- Needs Backend -->
            {% for no in range %}
            <div class="accordion div{{ no }}" id="accordionExample{{ no }}">
                {% for port in port_list %}
                {% if port.pironumber == no %}
                <div class="card">
                    <div class="card-header" data-toggle="collapse" data-target="#collapse{{ port.id }}"
                    aria-expanded="false" aria-controls="collapse{{ port.id }}">
                    <div class="text">
                        {{ port.title }}
                    </div>
                    <div class="icon fas fa-plus"></div>
                </div>
                    <div id="collapse{{ port.id }}" class="collapse" aria-labelledby="heading{{ port.id }}" data-parent="#accordionExample{{ no }}">
                        <div class="card-body">
                            <div class="row no-gutters">
                                <div class="col-md-4">
                                    {% if port.image %}
                                    <img src="{{ port.image.url }}" class="card-img" alt="..." style="padding: 20px; width: 350px; height: auto;">
                                    {% endif %}
                                </div>
                                <div class="col-md-8">
                                    <div class="card-body">
                                        <h5 class="card-title" style="font-family: 'Do Hyeon', Sans-Serif; text-align: left">{{port.pironumber}}기 {{ port.team }}, {{ port.title }}</h5>
                                        <p class="card-text" style="white-space: pre-wrap; font-family: 'Noto Sans KR', Sans-Serif">{{ port.content|urlize }}</p>
                                    </div> 
                                </div>
                            </div>
                                {% if user.is_admin %}
                                <div style="display: inline-block; float: right; margin-bottom: 5px;">
                                    <a class="btn-navy" href="{% url "home:port_edit" port.pk %}" style="margin-right: 5px; text-decoration: none;">수정</a>
                                    <a class="btn-navy" href="{% url "home:port_delete" port.pk %}" onclick="return confirm('삭제하시겠습니까?');" style="text-decoration: none;">삭제</a>
                                </div>
                                {% endif %}
                        </div>
                    </div>
                </div>
                {% endif %}
                {% endfor %}
            </div>
            {% endfor %}
        </div>
        {% if user.is_admin %}
        <div class="text-right" style="margin-right: 20px;">
            <a class="btn btn-navy" id="write_notice" href="{% url "home:port_new" %}" role="button"><i class="fas fa-pen" style="margin-right: 8px;"></i>프로젝트 추가하기</a>
        </div>
        {% endif %}
    </div>

</section>
{% endblock %}

external/templates/external/recruit.html
{% extends 'base.html' %}

{% block title %}
    피로그래밍 - 모집
{% endblock %}

{% block content %}

    {% load static %}


    <style>

        .img-header {
            background-image: url("{% static "img/board.jpg" %}");
        }

        .header-cover {
            background-color: rgba(47, 65, 84, 0.8);
        }

        #notice_list {
            padding: 40px 20px 30px 20px;
        }

        #notice_list a {
            text-decoration: none;
            color: #4f4f4f;
        }

        #notice_list a:hover {
            color: black;
            padding-bottom:20px;
        }

        /* 해결방안1-postion absolute 이용(단점: 높이 크게 고정해야함, 너무 긴 제목은 안됨) */

        /* .table-inner{
            height: 150px;
            position: relative;
            border-bottom: 0.5px solid #d6d6d6;
        } div
        .inner-right{
            float:right;
            position:absolute;
            left:230px;
            top:8px;
        } span
        .inner-left{
            float:left;
            position:absolute;
            top:10px;
        } span*/


        /* 해결방안2 -block & 넓이부여(단점: 창크기 조금만 줄여도 금방 내려감, bottom line 주면 이상해짐(width값때문에)) */

        .inner-left {
            display: block;
            width: 200px;
            margin-bottom: 10px;
        }

        .inner-right {
            display: block;
            width: 900px;

        }



    </style>

    <script>
        function change_recruit() {
            document.getElementById("option4").style.color = 'white';
            document.getElementById("option1").href = "{% url "home:home" %}#about";
            document.getElementById("option2").href = "{% url "home:home" %}#activity";
            document.getElementById("option3").href = "{% url "home:portfolio" %}";
        }

        change_recruit();

    </script>
    <div class="notice-list wow fadeInUp">
        <div class="img-header">
            <div class="header-content">
                <h3 class="header-title">RECRUITMENT</h3>
                <p class="header-text">피로그래밍 상세 모집일정과 관련 내용을 확인 하실 수 있습니다.</p>
            </div>
            <div class="header-cover"></div>
        </div>
        <!-- Needs Backend -->
        {% for message in messages %}
            <div class="alert alert-info">
                <a class="close" href="#" data-dismiss="alert">×</a>
                {{ message.message }}
            </div>
        {% endfor %}
        <div class="notice-table" style="margin-top: 50px;">
            <div class="row thead" style="margin:0px 5px;">
            </div>
            {% for notice in notice_list %}
                <div class="row nanum table-inner" id="notice_list">
            <span class="inner-left">
                <span>{{ notice.created_at }}</span>
            </span>
                    <span class="inner-right">
                <a href="{{ notice.get_absolute_url }}">
                    <span style="font-size: 25px; font-weight:bold;">{{ notice.title }}</span>
                    <!-- <span>피로그래밍 모집 공지입니다! 클릭하여 상세 내용을 확인해보세요!</span> -->
                </a>
            </span>
                </div>
            {% endfor %}
        </div>
        {% if user.is_admin %}
            <div class="text-right" style="margin-right:40px;">
                <a class="btn btn-navy" id="write_notice" href="{% url "home:recruit_new" %}" role="button">
                    <i class="fas fa-pen" style="margin-right: 8px;"></i>
                    글쓰기
                </a>
            </div>
        {% endif %}
    </div>
{% endblock %}