external/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('recruit/', views.recruit_list, name='recruit'),
    path('recruit/create/', views.recruit_new, name='recruit_new'),
    path('recruit/<int:pk>/', views.recruit_detail, name='recruit_detail'),
    path('recruit/<int:pk>/edit/', views.recruit_edit, name='recruit_edit'),
    path('recruit/<int:pk>/delete/', views.recruit_delete, name='recruit_delete'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('portfolio/create/', views.portfolio_new, name='port_new'),
    path('portfolio/<int:pk>/edit/', views.port_edit, name='port_edit'),
    path('portfolio/<int:pk>/delete/', views.port_delete, name='port_delete'),
]

infoboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from infoboard import views

app_name = 'infoboard'

urlpatterns = [
    path('<int:pk>/', views.detail_info, name='detail_info'),
    path('', views.list_info, name="list_info"),
    path('create/', views.create_info, name="create_info"),
    path('<int:pk>/update/', views.update_info, name="update_info"),
    path('<int:pk>/delete/', views.delete_info, name="delete_info"),
    path('<int:pk>/<int:img_pk>/download/', views.download, name="download"),
    path('bookmark_infoboard/<int:pk>/', views.create_bookmark_infoboard, name='create_bookmark_infoboard'),
]

if settings.DEBUG:
    urlpatterns += static(settings.INFO_MEDIA_URL, document_root=settings.MEDIA_ROOT)

internal/urls.py
from django.urls import path
from . import views

app_name = 'intranet'

urlpatterns = [
    path('', views.mainscreen, name='mainscreen'),
    path('qna/', views.qna, name='qna'),
    path('qna/create/', views.q_new, name='q_new'),
    path('qna/by_tag/', views.q_by_tag, name='q_by_tag'),
    path('qna/<int:pk>/', views.q_detail, name='q_detail'),
    path('qna/edit/<int:pk>/', views.q_edit, name='q_edit'),
    path('qna/delete/<int:pk>/', views.q_delete, name='q_delete'),
    path('qna/comment/<int:pk>/', views.comment_create, name='comment_create'),
    path('qna/comment/delete/<int:pk>/<int:cmt_pk>/', views.comment_delete, name='comment_delete'),
    path('qna/reply/<int:pk>/<int:cmt_pk>/', views.reply_create, name='reply_create'),
    path('qna/comment_like/', views.comment_like, name='comment_like'),
    path('address/', views.address_list, name='address_list'),
    path('address/create/', views.address_new, name='address_new'),
    path('address/edit/<int:pk>/', views.address_edit, name='address_edit'),
    path('address/delete/<int:pk>/', views.address_delete, name='address_delete'),
    path('checked/<int:pk>/', views.checked, name='checked'),
    path('checked_and_go/<int:pk>/<int:noti_pk>/', views.checked_and_go, name='checked_and_go'),
    # 내가 쓴 글 보기
    path('my_post/', views.my_post, name='my_post'),
    # qna 북마크
    path('bookmark_qna/<int:pk>/', views.create_bookmark_qna, name='create_bookmark_qna'),
    # 내가 북마크한 글 보기 / 삭제
    path('my_bookmark/', views.my_bookmark, name='my_bookmark'),
    path('my_bookmark/delete/delete/<int:pk>/',views.delete_bookmark, name = 'delete_bookmark')
]

money/urls.py
from django.urls import path

from money import views

app_name = 'money'

urlpatterns=[
    path('', views.check_money, name='check_money'),
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from ckeditor_uploader import views as uploader_views

urlpatterns = [
    path('', include('external.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('intranet/', include('internal.urls')),
    path('photobook/', include('photobook.urls')),
    path('money/', include('money.urls')),
    path('infoboard/', include('infoboard.urls')),
    path('ckeditor/upload/', uploader_views.upload, name='ckeditor_upload'),
    path('ckeditor/browse/', uploader_views.browse, name='ckeditor_browse'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

internal/models.py
import os

from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
from django.urls import reverse

from accounts.models import PiroUser

class Post(models.Model):
    title = models.CharField(max_length=100, verbose_name='제목')
    body = RichTextUploadingField(verbose_name='내용')
    tag = models.CharField(max_length=30)

    created_at = models.DateField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(PiroUser, on_delete=models.CASCADE, verbose_name='글쓴이')

    def __str__(self):
        return self.title


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    body = RichTextUploadingField(verbose_name='내용')

    deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(PiroUser, on_delete=models.CASCADE)

    like_user_set = models.ManyToManyField(PiroUser, blank=True, related_name='like_user_set',
                                           through='Like')

    like_num = models.IntegerField(default=0)

    def __str__(self):
        return f'{self.post}의 댓글'

    @property
    def like_count(self):
        return self.like_user_set.count()

    def delete(self):
        os.remove(self.file.path)
        return super(Comment, self).delete()

class Reply(models.Model):
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE, default=None)
    content = models.TextField(verbose_name='내용')

    deleted = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    author = models.ForeignKey(PiroUser, on_delete=models.CASCADE)
    
    def __str__(self):
        return f'{self.comment}의 답글'


class Like(models.Model):
    user = models.ForeignKey(PiroUser, on_delete=models.CASCADE)
    comment = models.ForeignKey(Comment, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)

class InfoBook(models.Model):
    user = models.ForeignKey(PiroUser, on_delete=models.CASCADE)
    current_work = models.CharField(max_length=100)
    piro_no = models.PositiveIntegerField()
    history = models.TextField()


class Notification(models.Model):
    TYPE_CHOICES = (
        ('좋아요', '좋아요'),
        ('댓글', '댓글'),
        ('답글', '답글'),
    )
    creator = models.ForeignKey(PiroUser, on_delete=models.CASCADE, related_name='creator')
    to = models.ForeignKey(PiroUser, on_delete=models.CASCADE, related_name='to')
    myid = models.CharField(max_length=250, null=True, blank= True)

    notification_type = models.CharField(max_length=20, choices=TYPE_CHOICES)

    checked = models.BooleanField(default=False)

internal/views.py
import json

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q, Max
from django.http import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse
from django.views.decorators.http import require_POST

from accounts.models import Bookmark
from infoboard.models import Info
from internal.forms import QuestionForm, CommentForm, ReplyForm, InfoBookForm
from photobook.models import Photobook
from .models import Post, Comment, InfoBook, Notification


@login_required
def mainscreen(request):
    question_recent = Post.objects.all().order_by('-id')[:2]
    info_recent = Info.objects.all().order_by('-id')[:2]
    photo_recent = Photobook.objects.all().order_by('-id')[:2]
    notifications = Notification.objects.filter(to=request.user, checked=False)
    return render(request, 'main_intranet.html', {
        'question_recent': question_recent,
        'info_recent': info_recent,
        'photo_recent': photo_recent,
        'notifications': notifications,
    })


def checked(request, pk):
    notification_check = request.POST.get('checked')
    if notification_check:
        notification = Notification.objects.get(pk=pk)
        notification.delete()
    return redirect('intranet:mainscreen')


def checked_and_go(request, pk, noti_pk):
    notification = Notification.objects.get(pk=pk)
    notification.delete()
    return redirect('intranet:q_detail', noti_pk)


@login_required
def qna(request):
    post_list = Post.objects.all().order_by('-id')

    total_len = len(post_list)
    page = request.GET.get('page', 1)
    paginator = Paginator(post_list, 10)

    try:
        questions = paginator.page(page)
    except PageNotAnInteger:
        questions = paginator.page(1)
    except EmptyPage:
        questions = paginator.page(paginator.num_pages)

    index = questions.number - 1
    max_index = len(paginator.page_range)
    start_index = index - 2 if index >= 2 else 0
    if index < 2:
        end_index = 5 - start_index
    else:
        end_index = index + 3 if index <= max_index - 3 else max_index
    page_range = list(paginator.page_range[start_index:end_index])

    return render(request, 'internal/qboard.html',
                  {'questions': questions, 'page_range': page_range, 'total_len': total_len,
                   'max_index': max_index - 2})


@login_required
def q_new(request, post=None):
    if request.method == 'POST':
        form = QuestionForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.tag = request.POST.get('tag')
            post.save()
            return redirect('intranet:q_detail', post.pk)
        else:
            return redirect("home:home")
    else:
        form = QuestionForm(instance=post)
        return render(request, 'internal/qcreate.html', {
            'form': form,
        })


def q_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.user == post.author:
        return q_new(request, post)
    else:
        return redirect('intranet:qna')


def q_delete(request, pk):
    post = Post.objects.get(id=pk)
    if request.user == post.author:
        post.delete()
        return redirect('intranet:qna')
    else:
        return redirect('intranet:qna')


@login_required
def q_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    # comment = post.comment_set.all()
    comment = post.comment_set.all().order_by('-like_num')
    comment_no = comment.count()
    form = CommentForm()
    form2 = ReplyForm()
    path = request.META.get('HTTP_REFERER')
    return render(request, 'internal/qdetail.html', {
        'post': post,
        'comment': comment,
        'comment_no': comment_no,
        'form': form,
        'form2': form2,
        'path': path,
    })


@login_required
def q_by_tag(request):
    if request.method == 'POST':
        post_list = Post.objects.all()
        tag = request.POST.get('tag')
        q = request.POST.get('q', '')

        if tag == 'all':
            pass
        else:
            post_list = post_list.filter(tag=tag).order_by('-id')

        if q:
            post_list = post_list.filter(Q(title__icontains=q) | Q(body__icontains=q)).order_by('-id')

        total_len = len(post_list)
        page = request.GET.get('page', 1)
        paginator = Paginator(post_list, 10)

        try:
            questions = paginator.page(page)
        except PageNotAnInteger:
            questions = paginator.page(1)
        except EmptyPage:
            questions = paginator.page(paginator.num_pages)

        index = questions.number - 1
        max_index = len(paginator.page_range)
        start_index = index - 2 if index >= 2 else 0
        if index < 2:
            end_index = 5 - start_index
        else:
            end_index = index + 3 if index <= max_index - 3 else max_index
        page_range = list(paginator.page_range[start_index:end_index])

        return render(request, 'internal/qboard.html',
                      {'questions': questions, 'tag': tag, 'page_range': page_range, 'total_len': total_len,
                       'max_index': max_index - 2})
    else:
        return redirect('intranet:qna')


@login_required
def comment_create(request, pk, comment=None):
    post = Post.objects.get(pk=pk)
    if request.method == 'POST':
        form = CommentForm(request.POST, request.FILES, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.save()
            if comment.author != comment.post.author:
                create_notification(comment.author, comment.post.author, '댓글', str(pk))
            return redirect('intranet:q_detail', post.pk)
    else:
        form = CommentForm(instance=comment)
        return render(request, 'internal/qdetail.html', {
            'form': form,
        })


@login_required
def comment_delete(request, pk, cmt_pk):
    post = Post.objects.get(pk=pk)
    comment = Comment.objects.get(pk=cmt_pk)
    comment.deleted = True
    comment.save()
    return redirect('intranet:q_detail', post.pk)


@login_required
def reply_create(request, pk, cmt_pk, reply=None):
    post = Post.objects.get(pk=pk)
    comment = Comment.objects.get(pk=cmt_pk)
    if request.method == 'POST':
        form = ReplyForm(request.POST, instance=reply)
        if form.is_valid():
            reply = form.save(commit=False)
            reply.comment = comment
            reply.author = request.user
            reply.save()
            if reply.author != reply.comment.author:
                create_notification(reply.author, reply.comment.author, '답글', str(post.pk))
            return redirect('intranet:q_detail', post.pk)
    else:
        form2 = ReplyForm(instance=reply)
        return render(request, 'internal/qdetail.html', {
            'form2': form2,
        })


@login_required
@require_POST  # 해당 뷰는 POST method 만 받는다.
def comment_like(request):
    pk = request.POST.get('pk', None)  # ajax 통신을 통해서 template에서 POST방식으로 전달
    comment = get_object_or_404(Comment, pk=pk)
    if hasattr(comment, 'like_user_set'):
        comment_like, comment_like_created = comment.like_set.get_or_create(user=request.user)
        if not comment_like_created:
            comment_like.delete()
            colortype = 'black'
        else:
            colortype = 'red'

        comment.like_num = comment.like_count
        comment.save()
        if request.user != comment.author:
            create_notification(request.user, comment.author, '좋아요', str(comment.post.pk))

        context = {'like_count': comment.like_count,
                   'nickname': str(request.user),
                   'comment_like_created': comment_like_created,
                   'colortype': colortype,
                   }
        return HttpResponse(json.dumps(context), content_type="application/json")


def create_notification(creator, to, notification_type, myid):
    notification = Notification.objects.create(
        creator=creator,
        to=to,
        notification_type=notification_type,
        myid=myid
    )
    notification.save()


def address_list(request):
    qs = InfoBook.objects.all().order_by('piro_no')
    maxpiro = InfoBook.objects.aggregate(Max('piro_no'))
    if maxpiro.get("piro_no__max") == None:
        return redirect("intranet:address_new")
    maxno = maxpiro.get("piro_no__max") + 1
    return render(request, 'internal/address.html', {
        'address_list': qs,
        'maxno': maxno,
        'range': range(1, maxno)
    })


@login_required
def address_new(request, address=None):
    if request.method == 'POST':
        form = InfoBookForm(request.POST, instance=address)
        if form.is_valid():
            address = form.save(commit=False)
            address.user = request.user
            address.piro_no = request.user.piro_no
            address.save()
            return redirect("intranet:address_list")
        else:
            return redirect("intranet:address_list")
    else:
        if InfoBook.objects.filter(user=request.user).exists():
            messages.error(request, '이미 주소록에 등록되어 있습니다.')
            return redirect("intranet:address_list")
        elif request.user.is_admin:
            messages.error(request, '운영진은 주소록을 등록할 수 없습니다.')
            return redirect("intranet:mainscreen")
        else:
            form = InfoBookForm(instance=address)
            return render(request, 'internal/create_address.html', {
                'form': form,
            })


@login_required
def address_edit(request, pk):
    address = get_object_or_404(InfoBook, pk=pk)

    if request.method == 'POST':
        form = InfoBookForm(request.POST, request.FILES)

internal/templates/internal/create_address.html
{% extends 'base_internal.html' %}

{% block title %}
피로그래밍 - 주소록 추가하기
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
{% if user.is_authenticated %}

<style>

#rec_upld{
        color:#57a0d3; 
        border: solid 1px#57a0d3;
    }
    #rec_upld:hover{
        background-color:#57a0d3;
        color:white;
    }

    .nanum {
        margin-bottom: 25px;
    }

    textarea.form-control{
        height: 150px;
    }

</style>

<script>
function change_address() {
    document.getElementById("option4").style.color = 'white';
}
change_address();
</script>

<div class="col-lg-7 col-md-8 col-11" style="margin:50px auto;">
    <h2 class="create-title" style="margin-bottom:0px;">주소록 등록</h2>
    <small>기수, 이름, 전화번호와 이메일 주소는 회원가입시 등록된 정보가 자동 사용됩니다.</small>

    <form action="" method="post" enctype="multipart/form-data">
        {% csrf_token %}
            <br>
            <div class="signup-form nanum">
                {{ form.current_work |as_crispy_field }}
            </div>
            <div class="signup-form nanum">
                {{ form.history|as_crispy_field }}
            </div>
            <button type="submit" id="rec_upld" class="btn">등록</button>
    </form>
</div>
{% else %}
<script>
    alert('접근 권한이 없는 페이지입니다.');
    window.location.href = "{% url "home:home" %}";
</script>
{% endif %}

{% endblock %}

internal/templates/internal/qdetail.html
{% extends 'base_internal.html' %}

{% load staticfiles %}
{% load custom_tags %}
{% load crispy_forms_tags %}

{% block title %}
    질문 #{{ post.id }}
{% endblock %}


{% block content %}

    <link rel="stylesheet"
          href="{% static 'ckeditor/ckeditor/plugins/codesnippet/lib/highlight/styles/railscasts.css' %}"/>
    <script src="{% static 'ckeditor/ckeditor/plugins/codesnippet/lib/highlight/highlight.pack.js' %}"></script>

    <style>
        .hljs{
            overflow-x: scroll;
        }

        .django-ckeditor-widget{
            width: 100%;
        }

        #cke_id_body{
            width: 100%;
        }
        p > img {
            max-width: 100% !important;
            height: auto !important;
        }
        
        #rec_upld{
        color: #57a0d3; 
        border: solid 1px #57a0d3;
        }

        #rec_upld:hover{
        background-color: #57a0d3;
        color:white;
        }

        textarea.form-control {
            height: 30px;
            border: none;
            resize: none;
        }

        textarea.form-control:focus {
            border: none;
            box-shadow: none;
        }

        textarea::placeholder {
            font-size: 0.8rem;
        }

        label.requiredField {
            display: none;
        }

        #reply {
            padding: 0.3rem 0;
        }

        .like {
            font-size: 35px;
        }

        i:hover{
            cursor: pointer;
            text-shadow: 0px 0px 2.5px lightslategrey;
        }

    </style>
    <script>
        function change_q() {
            document.getElementById("option2").style.color = 'white';
        }

        change_q();
    </script>
    <div class="col-sm-9" style="margin:50px auto;">
        <h2 class="nanum" style="font-size: 2rem; white-space: pre-line; line-height: 150%;">
            #{{ post.id }} | {{ post.title }}</h2>
        <hr/>
        <div class="nanum" style="padding:0; font-size:1rem; color:#888;">
            {% if post.author.img_profile %}
                <img src="{{ post.author.img_profile.url }}"
                     style="border:1px solid #2C3E52; border-radius: 50%; width:30px; height: 30px"/>
            {% else %}
                <img class="img_profile" src="https://cdn4.iconfinder.com/data/icons/political-elections/50/48-512.png"
                     style="border:1px solid #2C3E52; border-radius: 50%; width:30px; height: 30px"/>
            {% endif %}
            {{ post.author.username }} ({{ post.author.piro_no }}기)
            <div style="display: inline-block; float: right; color:#AAA;">
                {{ post.updated_at |date:"Y.m.d H:i" }}
            </div>
        </div>
        <hr/>
        <div class="nanum">
            <p style="color:dimgrey; font-size: 0.8rem; text-align: right; margin-bottom: 10px;">태그: {{ post.tag }}</p>
            <p style="white-space: pre-wrap;word-wrap:break-word;">{{ post.body | safe }}</p>
        </div>
        <br>
        <br>
        <div class="nanum" style="font-size:1.5rem;">
            답변 {{ comment_no }}
        </div>
        <hr/>
        {% for i in comment %}
            <div class="row nanum"
                 style="padding:0; font-size:1rem; color:#888; margin-bottom: 12px;">
                <div class="col-md-1"></div>
                <div class="col-md-11">
                    {% if i.author.img_profile %}
                        <img src="{{ i.author.img_profile.url }}"
                             style="border:1px solid #2C3E52; border-radius: 50%; width:30px; height: 30px"/>
                    {% else %}
                        <img class="img_profile"
                             src="https://cdn4.iconfinder.com/data/icons/political-elections/50/48-512.png"
                             style="border:1px solid #2C3E52; border-radius: 50%; width:30px; height: 30px;"/>
                    {% endif %}
                    {{ i.author.username }} ({{ i.author.piro_no }}기)
                    <div style="display: inline-block; float: right; color:#AAA;">
                        {{ i.updated_at |date:"Y.m.d H:i" }}
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-1">
                    <div><i class="fas fa-thumbs-up like" name="{{ i.id }}" id="lol-{{ i.id }}"
                            style="text-align:center; {% liked_by_user i.id request.user as liked_by_user_flag %} {% if liked_by_user_flag %} color:red {% endif %}"></i>
                    </div>
                    <br>
                    <div id="count-{{ i.id }}"
                         class="nanum" style="text-align:center; font-size: 25px;">{{ i.like_count }}</div>
                </div>
                <div class="col-md-11">
                    {% if i.deleted %}
                        <p style="color: dimgrey;">(삭제된 답변입니다.)</p>
                    {% else %}
                        {{ i.body | safe }}
                        {% if request.user == i.author %}
                            <div style="text-align: right">
                                <a class="btn-sky" style="font-size: 13px; text-decoration: none" href="{% url "intranet:comment_delete" post.pk i.pk %}"
                                   onclick="return confirm('삭제하시겠습니까?');">삭제</a>
                            </div>
                        {% endif %}
                    {% endif %}

                    {% for j in i.reply_set.all %}
                        <div style="border-top:0.0714285714rem solid #E1E7EB;">
                            <div style="font-size: 0.8rem; padding: 0.3rem 0;">
                                {{ j.content }}
                                <span style="color:#AAA;">
                            {{ j.author.username }} ({{ j.author.piro_no }}기)
                                {{ j.updated_at|date:"Y.m.d H:i" }}
                        </span>
                            </div>
                        </div>
                    {% endfor %}
                    <div style="border-top:0.0714285714rem solid #E1E7EB;"></div>
                    <form action="{% url "intranet:reply_create" post.pk i.pk %}" method="post"
                          enctype="multipart/form-data" autocomplete="off">
                        {% csrf_token %}
                        <div class="row" id="reply">
                            <div class="col-md-11">
                                {{ form2.content | as_crispy_field }}
                            </div>
                            <div class="col-md-1">
                                <input type="submit" value="입력" id="rec_upld" class="btn"
                                       style="height:25px; width: 40px; font-size: 0.7rem; padding:0;"/>
                            </div>
                        </div>
                        <br>
                    </form>
                </div>
            </div>
            <hr/>
            <br>
        {% endfor %}

        <div class="nanum" style="font-size:1.5rem;">
            답변하기
        </div>
        <br>
        <form action="{% url "intranet:comment_create" post.pk %}" method="post" enctype="multipart/form-data"
              autocomplete="off">
            {% csrf_token %}
            <div class="signup-form">
                {{ form.body | safe }}
                {{ form.media }}
            </div>
            <br>
            <input type="submit" value="답변 등록하기" id="rec_upld" class="btn"/>
        </form>
        <hr>
        <div style="display: inline-block; float: left;">
            <a class="btn-sky" href="{% url 'intranet:qna' %}" style="text-decoration: none">목록</a>
            <a class="btn-sky" href="javascript:history.go(-1);" style="text-decoration: none">이전</a>
        </div>
        {% if user.is_authenticated %}
            <div style="display: inline-block; float: right;">
                <a class="btn-sky" href="{% url 'intranet:create_bookmark_qna' post.pk %}" onclick="alert('스크랩 되었습니다.')" style="text-decoration: none; margin-right: 5px;">스크랩</a>
                {% if request.user == post.author %}
                <a class="btn-sky" href="{% url "intranet:q_edit" post.pk %}" style="margin-right: 5px; text-decoration: none">수정</a>
                <a class="btn-sky" href="{% url "intranet:q_delete" post.pk %}" onclick="return confirm('삭제하시겠습니까?');" style="text-decoration: none">삭제</a>
                {% endif %}
            </div>
        {% endif %}
        <br>
    </div>
    <script>hljs.initHighlightingOnLoad();</script>

    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script type="text/javascript">
        $(".like").click(function () {
            var pk = $(this).attr('name')
            $.ajax({ // .like 버튼을 클릭하면 <새로고침> 없이 ajax로 서버와 통신하겠다.
                type: "POST", // 데이터를 전송하는 방법을 지정
                url: "{% url 'intranet:comment_like' %}", // 통신할 url을 지정
                data: {'pk': pk, 'csrfmiddlewaretoken': '{{ csrf_token }}'}, // 서버로 데이터 전송시 옵션
                dataType: "json", // 서버측에서 전송한 데이터를 어떤 형식의 데이터로서 해석할 것인가를 지정, 없으면 알아서 판단

                // 서버측에서 전송한 Response 데이터 형식 (json)
                // {'likes_count': article.like_count, 'message': message }

                success: function (response) { // 통신 성공시 - 동적으로 좋아요 갯수 변경, 유저 목록 변경
                    $("#count-" + pk).html(response.like_count);
                    $("#lol-" + pk).css("color", response.colortype);
                },
                error: function (request, status, error) { // 통신 실패시 - 로그인 페이지 리다이렉트
                    alert("로그인이 필요합니다.")
                    window.location.replace("/accounts/login/")
                    //alert("code:"+request.status+"\n"+"message:"+request.responseText+"\n"+"error:"+error);
                },
            });
        })
    </script>
{% endblock %}