accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import UserCreateView, login, profile, profile_update, password_change

app_name = 'accounts'

urlpatterns = [
    path('signup/', UserCreateView.as_view(), name='signup'),
    path('login/', login, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', profile, name='profile'),
    path('profile/update/', profile_update, name='profile_update'),
    path('password_change/', password_change, name='password_change'),
]

external/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('recruit/', views.recruit_list, name='recruit'),
    path('recruit/create/', views.recruit_new, name='recruit_new'),
    path('recruit/<int:pk>/', views.recruit_detail, name='recruit_detail'),
    path('recruit/<int:pk>/edit/', views.recruit_edit, name='recruit_edit'),
    path('recruit/<int:pk>/delete/', views.recruit_delete, name='recruit_delete'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('portfolio/create/', views.portfolio_new, name='port_new'),
    path('portfolio/<int:pk>/edit/', views.port_edit, name='port_edit'),
    path('portfolio/<int:pk>/delete/', views.port_delete, name='port_delete'),
]

money/urls.py
from django.urls import path

from money import views

app_name = 'money'

urlpatterns=[
    path('', views.check_money, name='check_money'),
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from ckeditor_uploader import views as uploader_views

urlpatterns = [
    path('', include('external.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('intranet/', include('internal.urls')),
    path('photobook/', include('photobook.urls')),
    path('money/', include('money.urls')),
    path('infoboard/', include('infoboard.urls')),
    path('ckeditor/upload/', uploader_views.upload, name='ckeditor_upload'),
    path('ckeditor/browse/', uploader_views.browse, name='ckeditor_browse'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.conf import settings
from django.contrib.auth.models import BaseUserManager, AbstractUser
from django.db import models

class Profile(models.Model):
    user = models.OneToOneField(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)


class PiroUserManager(BaseUserManager):
    def create_user(self, email, name, username, phone_no, piro_no, img_profile, left_over, github, password=None):
        if not email:
            raise ValueError('이메일을 입력하시오.')

        user = self.model(
            email=self.normalize_email(email),
            name=name,
            username = username,
            phone_no = phone_no,
            piro_no = piro_no,
            img_profile = img_profile,
            left_over = left_over,
            github = github,
        )
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, username, password):
        name = '운영진'
        phone_no = '010-0000-0000'
        piro_no = 99999999
        img_profile = None
        left_over = 99999999
        github = 'https://github.com/pirogramming/'
        user = self.create_user(
            email,
            password=password,
            name=name,
            username=username,
            phone_no=phone_no,
            piro_no=piro_no,
            img_profile=img_profile,
            left_over=left_over,
            github = github,
        )
        user.is_active=True
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class PiroUser(AbstractUser):
    email = models.EmailField(max_length=255, unique=True, verbose_name='이메일')
    name = models.CharField(max_length=10, verbose_name='이름 (본명)')
    username = models.CharField(max_length=10, unique=True, verbose_name='아이디/ 닉네임')
    phone_no = models.CharField(max_length=20, verbose_name='전화번호')
    piro_no = models.PositiveIntegerField(verbose_name='기수')
    img_profile = models.ImageField(upload_to="user", blank= True, default=None, verbose_name='프로필 사진')
    left_over = models.PositiveIntegerField(blank=True, default=200000, verbose_name='보증금')
    github = models.URLField(verbose_name='깃허브 주소', blank=True)

    is_active = models.BooleanField(default=False)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)

    objects = PiroUserManager()

    def __str__(self):
        return f'{self.name}'

class Bookmark(models.Model):
    pirouser = models.ForeignKey(PiroUser, on_delete=models.CASCADE)
    bookmark_title = models.CharField(max_length=250)
    bookmark_num = models.CharField(max_length=250)
    bookmark_type = models.CharField(max_length=250)
    
    def __str__(self):
        return f'{self.pirouser}의 스크랩- {self.bookmark_num}'

accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import PiroUser



class SignUpForm(UserCreationForm):

    def __init__(self, *args, **kwargs):
        super(SignUpForm, self).__init__(*args, **kwargs)
        self.fields['password1'].label = '비밀번호'
        self.fields['password2'].label = '비밀번호 확인'

        self.fields['password1'].help_text = "8자 이상, 영문 숫자 특수문자 중 둘 이상을 섞어주세요"
        self.fields['password2'].help_text = "비밀번호를 한번 더 입력해주세요"

        self.fields['name'].widget.attrs['placeholder'] = '예) 홍길동'
        self.fields['phone_no'].widget.attrs['placeholder'] = '예) 010-1234-5678'
        self.fields['piro_no'].widget.attrs['placeholder'] = '예) 12'
        self.fields['github'].widget.attrs['placeholder'] = '예) https://github.com/pirogramming'

    class Meta:
        model = PiroUser
        fields = ['email', 'name', 'username', 'phone_no', 'piro_no', 'img_profile', 'github']

        help_texts = {
            'email': ('이메일 형식에 맞게 적어주세요'),
            'phone_no': ('"-" 를 포함해서 입력해주세요'),
            'piro_no': ('숫자만 입력 가능합니다.'),
            'img_profile': ('25MB이하 파일만 가능합니다'),
            'github': ('깃허브 링크를 입력해주세요.'),
        }

    def saved(self):
        user = super().save()
        PiroUser.objects.create(
            user=user,
            email=self.cleaned_data['email'],
            name=self.cleaned_data['name'],
            username=self.cleaned_data['username'],
            phone_no=self.cleaned_data['phone_no'],
            piro_no=self.cleaned_data['piro_no'],
            img_profile=self.cleaned_data['img_profile'],
            github=self.cleaned_data['github']
        )
        return user


class LoginForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(LoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].label = '아이디/ 닉네임'
        self.fields['password'].label = '비밀번호'

    class Meta:
        model = PiroUser
        widgets = {'password': forms.PasswordInput}
        fields = ['username', 'password']


class UserEditForm(UserChangeForm):
    def __init__(self, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)

    class Meta:
        model = PiroUser
        fields = ['email', 'username', 'phone_no', 'img_profile', 'github']

        help_texts = {
            'email': ('이메일 형식에 맞게 적어주세요'),
            'nickname': ('다섯자 이하로 입력하세요'),
            'img_profile': ('25MB이하 파일만 가능합니다'),
            'github': ('깃허브 링크를 입력해주세요.'),
        }

accounts/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, update_session_auth_hash, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.messages.views import SuccessMessageMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect

from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView
from .forms import SignUpForm, LoginForm, UserEditForm
from .models import PiroUser


class UserCreateView(SuccessMessageMixin, CreateView):
    template_name = 'accounts/signup_form.html'
    form_class = SignUpForm
    success_url = reverse_lazy('accounts:login')


def login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        user = authenticate(username=username, password=password)

        if user is not None:
            auth_login(request, user)
            if user.is_admin:
                return HttpResponseRedirect(reverse('admin:index'))
            else:
                return redirect('home:home')
        else:
            try:
                user = PiroUser.objects.get(username=username)
                messages.error(request, '운영진의 인증이 완료되지 않은 계정입니다.')
                return redirect('accounts:login')
            except:
                messages.error(request,'아이디나 비밀번호를 확인해주세요.')
                return redirect('accounts:login')
    else:
        form = LoginForm()
    return render(request, 'accounts/login_form.html', {'form': form})


@login_required
def profile(request):
    return render(request, 'accounts/profile.html')

@login_required
def profile_update(request):
    if request.method == 'POST':
        form = UserEditForm(request.POST, request.FILES, instance=request.user)
        if form.is_valid():
            done = form.save()
            return redirect("accounts:profile")
    else:
        profileform = UserEditForm(instance=request.user)
        forms = {'profileform': profileform}
        return render(request, 'accounts/profile_update.html', forms)

@login_required
def password_change(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            # Now an important bit is to call update_session_auth_hash() after you save the form. Otherwise the user’s auth session will be invalidated and she/he will have to log in again.
            messages.success(request, '비밀번호가 변경되었습니다. 변경된 비밀번호로 다시 로그인 해보세요.')
            logout(request)
            return redirect('accounts:login')
        else:
            messages.error(request, '오류를 수정해주세요.')
    else:
        form = PasswordChangeForm(request.user)
    return render(request, 'accounts/password_change.html', {
        'form': form
    })

accounts/templates/accounts/base_accounts.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

    <main>
        {% block content %}
        {% endblock %}
    </main>

</body>
</html>

accounts/templates/accounts/home.html
{% extends 'accounts/base_accounts.html' %}

    {% block title %}Home{% endblock %}

    {% block content %}
        {% if user.is_authenticated %}
            Hi {{ user.username }}!
            <p><a href="{% url 'logout' %}">logout</a></p>
        {% else %}
            <p>You are not logged in</p>
            <a href="{% url 'login' %}">login</a> |
            <a href="{% url 'signup' %}">signup</a>
        {% endif %}
    {% endblock %}

accounts/templates/accounts/login_form.html
{% extends 'base.html' %}

{% block title %}
피로그래밍 - 로그인
{% endblock %}

{% load crispy_forms_tags %}

{% block content %}
<style>
    #login{
        color: #2F4154; 
        border: solid 1px #2F4154;
    }
    #login:hover{
        background-color: #2F4154;
        color:white;
    }
    #loginbutton a{
        text-decoration: none;
        color: #2F4154;
        font-family: 'Do Hyeon', sans-serif;
    }
    #loginbutton a:hover{
        color: #2C3E52;
    }
</style>
<script>
    function change_acct() {
    document.getElementById("option1").href="{% url "home:home" %}#about";
    document.getElementById("option2").href="{% url "home:home" %}#activity";
    document.getElementById("option3").href="{% url "home:portfolio" %}";
    document.getElementById("option4").href="{% url "home:recruit" %}";
}

    change_acct();
</script>
{% if not user.is_authenticated %}
    <div class="col-xl-5 col-lg-5 col-md-9 col-sm-9 col-xs-11" style="color:black; margin:50px auto;">
        <div style="background-color: white;border: #2F4154 solid 5px; padding:20px; border-radius: 20px; box-shadow: 3px 3px 20px 1px darkgray;">
            <div style="text-align: center;">
                <strong style="color: #2F4154; font-family: 'Do Hyeon', sans-serif; font-size: 40px;">로그인</strong>
                <br>
                <small>운영진의 인증이 완료된 계정만 로그인 가능합니다.</small><br/><br/>
            </div>
            <div style="margin: 0px 70px">
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {% for message in messages %}
                        <div class="alert alert-info">
                            <a class="close" href="#" data-dismiss="alert">×</a>
                            {{ message.message }}
                        </div>
                    {% endfor %}
                    <div>
                        {{ form.username|as_crispy_field }}
                    </div>
                    <div>
                        {{ form.password|as_crispy_field }}
                    </div>
                    <br/>
                    <input type="submit" class="btn" id="login" value="로그인">
                </form>
            </div>
            <div id='loginbutton' style="text-align: right">
                <a href="{% url 'accounts:signup' %}">회원가입</a>&nbsp;&nbsp;&nbsp;
                <a href="#" onclick="return alert('피로그래밍 운영진에게 문의하세요.');">비밀번호찾기</a>
            </div>
        </div>
    </div>
{% else %}
<script>
    alert('이미 로그인한 상태입니다.');
    window.location.href = "{% url "home:home" %}";
</script>
{% endif %}
{% endblock %}

accounts/templates/accounts/password_change.html
{% extends 'base.html' %}

{% block title %}
피로그래밍 - 비밀번호 변경
{% endblock %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
<style>
    #pass_save{
        color: #2F4154; 
        border: solid 1px #2F4154;
    }
    #pass_save:hover{
        background-color: #2F4154;
        color:white;
    }
</style>
<script>
    function change_acct() {
    document.getElementById("option1").href="{% url "home:home" %}#about";
    document.getElementById("option2").href="{% url "home:home" %}#activity";
    document.getElementById("option3").href="{% url "home:portfolio" %}";
    document.getElementById("option4").href="{% url "home:recruit" %}";
}

    change_acct();
</script>
    <div class="col-xl-5 col-lg-5 col-md-9 col-sm-9 col-xs-11" style="color:black; margin:50px auto;">
        <div style="background-color: white;border: #2F4154 solid 5px; padding:20px; border-radius: 20px; box-shadow: 3px 3px 20px 1px darkgray;">
            <div style="text-align: center;">
                <strong style="color: #2F4154; font-family: 'Do Hyeon', sans-serif; font-size: 40px;">비밀번호 변경</strong>
            </div>
            <div>
                <form action="" method="post">
                    {% csrf_token %}
                    <div style="padding-bottom: 5px"><br/>
                        <div class="signup-form">
                            {{ form.old_password|as_crispy_field }}
                        </div>
                        <div class="signup-form">
                            {{ form.new_password1|as_crispy_field }}
                        </div>
                        <div class="signup-form">
                            {{ form.new_password2|as_crispy_field }}
                        </div>
                    </div>
                    <input type="submit" class="btn" id="pass_save" value="저장하기">
                </form>
            </div>
        </div>
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base_internal.html' %}
{% load static %}
{% load humanize %}

{% block title %}
프로필
{% endblock %}

{% block content %}
<style>
    #profileb{
        color: #2F4154; 
        border: solid 1px #2F4154;
    }

    #profileb:hover{
        background-color: #2F4154;
        color:white;
    }

</style>
<div class="container">
    <br/>
    <div class="row">
        <div class="col-lg-12" style="font-size: 26px; border-bottom: 1px solid #d6d6d6; padding: 10px;">
            {% if user.img_profile %}
                <img class="img_profile" src="{{ user.img_profile.url }}" style="border:2px solid #2C3E52; border-radius: 50%; width:50px; height: 50px"/>
            {% else %}
                <img class="img_profile" src="https://cdn4.iconfinder.com/data/icons/political-elections/50/48-512.png" style="border:2px solid #2C3E52; border-radius: 50%; width:50px; height: 50px"/>
            {% endif %}
            <strong>  {{ user }}님의 프로필</strong>
            <div style="display: inline-block; float: right;">
                <a class="btn" id="profileb" href="{% url "accounts:logout" %}" role="button" >로그아웃</a>
            </div>
        </div>
        <div class="col-lg-12" style="font-family:'Noto Sans KR', Helvetica, Arial, sans-serif;">
            <div style="text-align: left; font-size: 20px;">
                <p style="margin-top: 15px;"><strong>아이디/ 닉네임 :</strong> {{ user.username }}</p>
                <p><strong>이름 :</strong> {{ user.name }}</p>
                <p><strong>이메일 :</strong> {{ user.email }}</p>
                <p><strong>전화번호 :</strong> {{ user.phone_no }}</p>
                <p><strong>기수 :</strong> {{ user.piro_no }}기</p>
                <p><strong>깃허브 주소 : </strong>{% if user.github == None %}등록된 깃허브 주소가 없습니다.{% else %}{{ user.github }}{% endif %}</p>
                <p><strong>보증금 상태 :</strong> {{ user.left_over|intcomma }}원</p>
                <span>
                    <a class="btn" id="profileb" href="{% url "accounts:profile_update" %}" role="button" style="margin-right: 15px;">프로필 정보 수정</a>
                    <a class="btn" id="profileb" href="{% url "accounts:password_change" %}" role="button" >비밀번호 변경</a>
                </span>
            </div>
        </div>
    </div>
    <br/>
</div>
{% endblock %}

accounts/templates/accounts/profile_update.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block title %}
피로그래밍 - 프로필 수정
{% endblock %}

{% block content %}
<style>
    #div_id_img_profile label{
        display: none;
    }
    #img_profile-clear_id{
        display:none
    }
    #prf_save{
        color: #2F4154; 
        border: solid 1px #2F4154;
    }
    #prf_save:hover{
        background-color: #2F4154;
        color:white;
    }

</style>
<script>
    function change_acct() {
    document.getElementById("option1").href="{% url "home:home" %}#about";
    document.getElementById("option2").href="{% url "home:home" %}#activity";
    document.getElementById("option3").href="{% url "home:portfolio" %}";
    document.getElementById("option4").href="{% url "home:recruit" %}";
}

    change_acct();
</script>
<div class="col-xl-7 col-lg-7 col-md-9 col-sm-11 col-xs-12" style="color:black; margin:50px auto;">
    <div style="background-color: white;border: #2F4154 solid 5px; padding:20px; border-radius: 20px; box-shadow: 3px 3px 20px 1px darkgray;">
        <div class="container">
                <strong style="color: #2F4154; font-family: 'Do Hyeon', sans-serif; font-size: 40px;">프로필 정보 수정</strong>
                <br>
                <br>
            <div class="row">
                <div class="col-lg-12">
                    <div>
                        <form action="" method="POST" enctype="multipart/form-data"> {% csrf_token %}
                            {% if user.img_profile %}
                                <div><img src="{{ user.img_profile.url }}"style="width:150px; height: 150px"/></div><br/>
                            {% else %}
                                <div><img src="https://cdn4.iconfinder.com/data/icons/political-elections/50/48-512.png" style="width:150px; height: 150px"/></div><br/>
                            {% endif %}
                            <div>{{ profileform.img_profile|as_crispy_field }}</div>
                            <div>{{ profileform.username|as_crispy_field }}</div>
                            <div>{{ profileform.email|as_crispy_field }}</div>
                            <div>{{ profileform.phone_no|as_crispy_field }}</div>
                            <div>{{ profileform.github|as_crispy_field }}</div>
                            <div>
                                <input type="submit" class="btn" id="prf_save" value="저장하기">
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

accounts/templates/accounts/signup_form.html
{% extends 'base.html' %}

{% block title %}
피로그래밍 - 회원가입
{% endblock %}

{% load staticfiles %}
{% load crispy_forms_tags %}

{% block content %}
    <style>
        #reg{
            width: 300px; 
            color: #2F4154; 
            border: solid 1px #2F4154;
        }
        #reg:hover{
            background-color: #2F4154;
            color:white;
        }
    </style>
<script>
    function change_acct() {
    document.getElementById("option1").href="{% url "home:home" %}#about";
    document.getElementById("option2").href="{% url "home:home" %}#activity";
    document.getElementById("option3").href="{% url "home:portfolio" %}";
    document.getElementById("option4").href="{% url "home:recruit" %}";
}

    change_acct();
</script>
{% if not user.is_authenticated %}
    <div class="col-xl-7 col-lg-7 col-md-9 col-sm-11 col-xs-12" style="color:#2F4154; margin:50px auto;">
        <div style="background-color: white;border:  solid 5px; padding:30px; border-radius: 20px; box-shadow: 3px 3px 20px 1px darkgray;">
            <div style="text-align: center;">
                <strong style="color: #2F4154; font-family: 'Do Hyeon', sans-serif; font-size: 40px;">피로그래밍 회원가입</strong>
                <br>
                <small>*표시된 항목은 필수항목 입니다</small><br/><br/>
            </div>
            <div>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                        <div class="row">
                            <div class="col-md-5 signup-form">
                                {{ form.name|as_crispy_field }}
                            </div>
                            <div class="col-md-7 signup-form">
                            {{ form.phone_no|as_crispy_field }}
                            </div>
                        </div>
                        <div class="signup-form">
                            {{ form.username|as_crispy_field }}
                        </div>
                        <div class="signup-form">
                            {{ form.password1|as_crispy_field }}
                        </div>
                        <div class="signup-form">
                            {{ form.password2|as_crispy_field }}
                        </div>
                        <h4 style="color: #2F4154; font-family: 'Do Hyeon', sans-serif; font-size: 30px; padding-bottom: 2px; border-bottom: solid 1px #2C3E52;">기타 프로필</h4>
                        <div class="signup-form">
                            {{ form.piro_no|as_crispy_field }}
                        </div>
                        <div class="signup-form">
                            {{ form.email|as_crispy_field }}
                        </div>
                        <div class="signup-form">
                            {{ form.img_profile|as_crispy_field }}
                        </div>
                        <div class="signup-form">
                            {{ form.github|as_crispy_field }}
                        </div>
                    <br/>
                    <div style="text-align: center;">
                    <input type="submit" class="btn btn" id="reg" value="회원가입">
                    </div>
                </form>
            </div>
        </div>
    </div>
{% else %}
<script>
    alert('이미 로그인한 상태입니다. 로그아웃 후 회원가입을 진행해주세요.');
    window.location.href = "{% url "home:home" %}";
</script>
{% endif %}

{% endblock %}