accounts/urls.py
from django.contrib.auth.views import LogoutView
from django.urls import path
from .views import UserCreateView, login, profile, profile_update, password_change

app_name = 'accounts'

urlpatterns = [
    path('signup/', UserCreateView.as_view(), name='signup'),
    path('login/', login, name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('profile/', profile, name='profile'),
    path('profile/update/', profile_update, name='profile_update'),
    path('password_change/', password_change, name='password_change'),
]

external/urls.py
from django.urls import path
from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
    path('recruit/', views.recruit_list, name='recruit'),
    path('recruit/create/', views.recruit_new, name='recruit_new'),
    path('recruit/<int:pk>/', views.recruit_detail, name='recruit_detail'),
    path('recruit/<int:pk>/edit/', views.recruit_edit, name='recruit_edit'),
    path('recruit/<int:pk>/delete/', views.recruit_delete, name='recruit_delete'),
    path('portfolio/', views.portfolio, name='portfolio'),
    path('portfolio/create/', views.portfolio_new, name='port_new'),
    path('portfolio/<int:pk>/edit/', views.port_edit, name='port_edit'),
    path('portfolio/<int:pk>/delete/', views.port_delete, name='port_delete'),
]

infoboard/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

from infoboard import views

app_name = 'infoboard'

urlpatterns = [
    path('<int:pk>/', views.detail_info, name='detail_info'),
    path('', views.list_info, name="list_info"),
    path('create/', views.create_info, name="create_info"),
    path('<int:pk>/update/', views.update_info, name="update_info"),
    path('<int:pk>/delete/', views.delete_info, name="delete_info"),
    path('<int:pk>/<int:img_pk>/download/', views.download, name="download"),
    path('bookmark_infoboard/<int:pk>/', views.create_bookmark_infoboard, name='create_bookmark_infoboard'),
]

if settings.DEBUG:
    urlpatterns += static(settings.INFO_MEDIA_URL, document_root=settings.MEDIA_ROOT)

internal/urls.py
from django.urls import path
from . import views

app_name = 'intranet'

urlpatterns = [
    path('', views.mainscreen, name='mainscreen'),
    path('qna/', views.qna, name='qna'),
    path('qna/create/', views.q_new, name='q_new'),
    path('qna/by_tag/', views.q_by_tag, name='q_by_tag'),
    path('qna/<int:pk>/', views.q_detail, name='q_detail'),
    path('qna/edit/<int:pk>/', views.q_edit, name='q_edit'),
    path('qna/delete/<int:pk>/', views.q_delete, name='q_delete'),
    path('qna/comment/<int:pk>/', views.comment_create, name='comment_create'),
    path('qna/comment/delete/<int:pk>/<int:cmt_pk>/', views.comment_delete, name='comment_delete'),
    path('qna/reply/<int:pk>/<int:cmt_pk>/', views.reply_create, name='reply_create'),
    path('qna/comment_like/', views.comment_like, name='comment_like'),
    path('address/', views.address_list, name='address_list'),
    path('address/create/', views.address_new, name='address_new'),
    path('address/edit/<int:pk>/', views.address_edit, name='address_edit'),
    path('address/delete/<int:pk>/', views.address_delete, name='address_delete'),
    path('checked/<int:pk>/', views.checked, name='checked'),
    path('checked_and_go/<int:pk>/<int:noti_pk>/', views.checked_and_go, name='checked_and_go'),
    # 내가 쓴 글 보기
    path('my_post/', views.my_post, name='my_post'),
    # qna 북마크
    path('bookmark_qna/<int:pk>/', views.create_bookmark_qna, name='create_bookmark_qna'),
    # 내가 북마크한 글 보기 / 삭제
    path('my_bookmark/', views.my_bookmark, name='my_bookmark'),
    path('my_bookmark/delete/delete/<int:pk>/',views.delete_bookmark, name = 'delete_bookmark')
]

money/urls.py
from django.urls import path

from money import views

app_name = 'money'

urlpatterns=[
    path('', views.check_money, name='check_money'),
]

website/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from ckeditor_uploader import views as uploader_views

urlpatterns = [
    path('', include('external.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('intranet/', include('internal.urls')),
    path('photobook/', include('photobook.urls')),
    path('money/', include('money.urls')),
    path('infoboard/', include('infoboard.urls')),
    path('ckeditor/upload/', uploader_views.upload, name='ckeditor_upload'),
    path('ckeditor/browse/', uploader_views.browse, name='ckeditor_browse'),
]


urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>

    <!-- FONTAWESOME -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.6.3/css/all.css"
        integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <!-- OTHER FONTS USED -->
    <link href="https://fonts.googleapis.com/css?family=Advent+Pro|Dosis|Nanum+Gothic&display=swap" rel="stylesheet">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">

    <!-- JS -->
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/menuspy.min.js' %}"></script>
    <script>
        $(document).ready(function(){
        $('.counter').counterUp();
        });
    </script>
    <script>
    $(function(){
        $('#back-to-top').on('click',function(e){
            e.preventDefault();
            $('html,body').animate({scrollTop:0},80);
    });

    $(window).scroll(function() {
        if ($(document).scrollTop() > 100) {
            $('#back-to-top').addClass('show');
        } else {
            $('#back-to-top').removeClass('show');
        }
        });
    });
    </script>
    <script>
        new WOW().init();
    </script>
    <script>
    $(document).ready( function() {
        $("#progress-container").hide();
        $(".dodobird").css("display", ""); //hide your div initially
        var botOfOthDiv = $("#home").position().top + $("#home").outerHeight(true) - '70';
        $(window).scroll(function() {
            if($(window).scrollTop() >= botOfOthDiv) { //scrolled past the other div?
                $(".dodobird").css("display", "none");
                $("#progress-container").show(); //reached the desired point -- show div
            }
            else{
                $("#progress-container").hide();
                $(".dodobird").css("display", "");
            }
        });
    });
    </script>
    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>


<body>
    <a id="back-to-top" href="#home"></a>
    {% include 'navbar.html' %}

    {% block content %}
    {% endblock %}

    {% include 'footer.html' %}

    {% block script %}
    {% endblock %}
</body>
<script>
    var elm = document.querySelector('#navbar');
    var ms = new MenuSpy(elm);
</script>
</html>

templates/base_internal.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <!-- BOOTSTRAP -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
            integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
            integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
            crossorigin="anonymous"></script>

    <!-- FONTAWESOME -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//use.fontawesome.com/releases/v5.6.3/css/all.css"
          integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous">

    <!-- OTHER FONTS USED -->
    <link href="https://fonts.googleapis.com/css?family=Advent+Pro|Dosis|Nanum+Gothic&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Gugi|Yeon+Sung&display=swap" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Baloo+Paaji' rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Nanum+Pen+Script&display=swap" rel="stylesheet">

    <!-- CSS -->
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <link rel="stylesheet" href="{% static "css/lightbox.css" %}">

    <!-- JS -->
    <script src="{% static 'js/wow.min.js' %}"></script>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js"></script>
    <script src="{% static 'js/jquery.counterup.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/menuspy.min.js' %}"></script>
    <script>
        $(document).ready(function () {
            $('.counter').counterUp();
        });
    </script>
    <script>
        $(function () {
            $('#back-to-top').on('click', function (e) {
                e.preventDefault();
                $('html,body').animate({scrollTop: 0}, 80);
            });

            $(window).scroll(function () {
                if ($(document).scrollTop() > 100) {
                    $('#back-to-top').addClass('show');
                } else {
                    $('#back-to-top').removeClass('show');
                }
            });
        });
    </script>
    <script>
        new WOW().init();
    </script>


    <title>
        {% block title %}
        {% endblock %}
    </title>
</head>

<body>
<a id="back-to-top" href="#home"></a>
{% include 'navbar_internal.html' %}

{% block content %}
{% endblock %}


{% block script %}
{% endblock %}
</body>
<script>
    var elm = document.querySelector('#navbar');
    var ms = new MenuSpy(elm);
</script>
</html>

templates/footer.html
<div id="foot">
    <div class="footer-buffer"></div>
    <div class="contact">
        <a href="https://www.facebook.com/p.rogramming3k/" target="_blank" style="text-decoration: none">
            <i class="fab fa-facebook fa-2x"></i>
        </a>
        <a href="mailto:pirogramming@gmail.com" style="text-decoration: none">
            <i class="fas fa-envelope fa-2x"></i>
        </a>
    </div>
    <footer class="container-fluid d-flex flex-column justify-content-center">
        <div class="row d-flex justify-content-center">
            &copy피로그래밍 | 회장 : 정성모 | 연락처: 010-1234-5678
        </div>
        <div class="row mt-1 d-flex justify-content-center" style="margin-bottom: 1%">
            서울특별시 관악구 관악로 1, 서울대학교 벤처경영 교육 및 연구 동아리
        </div>
    </footer>
</div>

templates/navbar.html
{% load staticfiles %}
<div id="sticks">
<nav class="navbar navbar-expand-md navbar-dark" id="navbar">
    <div class="navbar-header">
        <a class="navbar-logo" href="{% url "home:home" %}">
        <img src="{% static 'img/piro_logo.jpg' %}" alt="piro_logo">
    </a>
    </div>

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
              <a class="nav-link" id="option1" href="#about">ABOUT US</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#activity" id="option2">ACTIVITY </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#port" id="option3">PORTFOLIO </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url "home:recruit" %}" id="option4">RECRUITMENT </a>
          </li>
            {% if user.is_authenticated %}
          <li class="nav-item">
            <a class="nav-link" href="{%url "intranet:mainscreen"%}" id="option5">BOARD </a>
          </li>
            {% endif %}
        </ul>
        <ul class="nav navbar-nav navbar-right" id="sign-up">
            {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link" href="{% url "accounts:logout" %}"><i class="fas fa-sign-out-alt"></i>LOGOUT</a></li>
            {% else %}
                <li class="nav-item"><a class="nav-link"  href="{% url "accounts:signup" %}"><i class="fas fa-user"></i>SIGN UP</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url "accounts:login" %}"><i class="fas fa-sign-in-alt"></i>LOGIN</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
<div id="progress-container">
    <div class="progress-bar" id="myBar"></div>
</div>
</div>

templates/navbar_internal.html
{% load staticfiles %}
<script src='https://code.jquery.com/jquery-3.2.1.min.js'></script>
<script>
window.onscroll = function() {navFunction();};

function navFunction() {
  if (document.body.scrollTop > 80 || document.documentElement.scrollTop > 80) {
    document.getElementById("navbar-inter").style.backgroundColor = "#2d3142";
  } else {
    document.getElementById("navbar-inter").style.backgroundColor = "#AAD6EC";
  }
}
</script>
<style>
    #navbar-inter{
        background-color: #AAD6EC;
    }
    .nav-link {
        text-decoration: none;
        color:white;
        font-family: 'Do Hyeon';
    }

    .piro-nav{
        font-family: 'Gugi';
        font-size:23px; 
        width:130px; 
        color:white; 
        margin-left:5%; 
        margin-bottom: 0
    }

    .navbar-logo:hover{
        text-shadow:0px 0px 2.5px white;
    }
</style>

<div id="sticks">
<nav class="navbar navbar-expand-md" id="navbar-inter" style="padding: 1%;">
        <a class="navbar-logo" href="{% url "intranet:mainscreen" %}" style="text-decoration: none;">
            <p class="piro-nav">피로그래밍</p>
        </a>
    

    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"
            style="color:white;">
        <span class="navbar-toggler-icon" style="color:white;"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item">
                <a class="nav-link btn-nav" id="option1" href="{% url "infoboard:list_info" %}">정보게시판</a>
            </li>
            <li class="nav-item">
                <a class="nav-link btn-nav" href="{% url "intranet:qna" %}" id="option2">질문게시판 </a>
            </li>
            <li class="nav-item">
                <a class="nav-link btn-nav" href="{% url "photobook:list_book" %}" id="option3">사진첩 </a>
            </li>
            <li class="nav-item">
                <a class="nav-link btn-nav" href="{% url "intranet:address_list" %}" id="option4">회원주소록 </a>
            </li>
            {% if user.is_admin %}
            <li class="nav-item">
                <a class="nav-link btn-nav" href="{% url 'admin:index' %}" id="option5">관리자 페이지 </a>
            </li>
            {% endif %}
            <li class="nav-item">
                <a class="nav-link btn-nav" href="{% url "home:home" %}" id="option6">홈페이지 </a>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right" id="sign-up">
            {% if user.is_authenticated %}
                <li class="nav-item"><a class="nav-link btn-nav" href="{% url "accounts:logout" %}"><i
                        class="fas fa-sign-out-alt"></i>LOGOUT</a></li>
            {% else %}
                <li class="nav-item"><a class="nav-link btn-nav" href="{% url "accounts:signup" %}"><i class="fas fa-user"></i>SIGN
                    UP</a></li>
                <li class="nav-item"><a class="nav-link btn-nav" href="{% url "accounts:login" %}"><i
                        class="fas fa-sign-in-alt"></i>LOGIN</a></li>
            {% endif %}
        </ul>
    </div>
</nav>
</div>